{% set name = "legate-core" %}
{% if package_version is defined %}
    {% set version = package_version %}
## The tag must be in one of the two formats (where N is a digit):
## vNN.NN.NN
## vNN.NN.NN.dev
{% elif 'dev' in environ.get('GIT_DESCRIBE_TAG', '') %}
    {% set version = (environ.get('GIT_DESCRIBE_TAG', '') ~ environ.get('GIT_DESCRIBE_NUMBER', '')).lstrip('v') %}
{% else %}
    {% set version = environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') %}
{% endif %}
{% set cuda_version='.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
{% if package_tar is defined %}
  url: {{ package_tar }}
{% else %}
  git_url: ../../
{% endif %}

build:
  skip: true # [not linux]
  number: {{ GIT_DESCRIBE_NUMBER }}
  missing_dso_whitelist:
    -  '*libcuda.so*'
  string: "cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ PKG_BUILDNUM }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - zlib
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - cuda-compiler >={{ cuda_version }}
    - cuda-libraries-dev >={{ cuda_version }}
    - cudatoolkit >={{ cuda_version }}
    - nccl
  run:
    - python
    - cudatoolkit >={{ cuda_version }}
    - openmp
    - zlib
    - numpy
    - cffi
    - pyarrow >=5.0.0
    
  run_constrained:
    - __cuda >= 8.0
    - __glibc >=2.17  # [linux]

test:
  imports:
    - legate

about:
  home: https://github.com/nv-legate/legate.core
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Scalable Computational Code'
  description: |
    The Legate project endeavors to democratize computing by 
    making it possible for all programmers to leverage the power 
    of large clusters of CPUs and GPUs by running the same code 
    that runs on a desktop or a laptop at scale.
  doc_url: https://github.com/nv-legate/legate.core
  dev_url: https://github.com/nv-legate/legate.core

extra:
  recipe-maintainers:
    - m3vaz
