repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
            - id: isort
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
            - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
            - id: flake8
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v15.0.7'
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cc|inl)$
          types_or: []
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.1.1'
      hooks:
        - id: mypy
          pass_filenames: false
          args: ['legate', 'tests']
          additional_dependencies: [numpy,pytest,pytest_mock]
default_language_version:
    python: python3
