#!/usr/bin/env bash

build_legate_wheel() {
    set -xeuo pipefail;

    rm -rf $REPO_DIR/_skbuild;

    mkdir -p /tmp/out;

    local pip_args=(-vv);
    pip_args+=(--wheel-dir /tmp/out);

    if type conda 2>&1 >/dev/null; then
        pip_args+=(--no-deps);
        pip_args+=(--no-build-isolation);
    fi

    local ninja_args=();
    ninja_args+=("-v");
    ninja_args+=("-j${JOBS:-$(nproc --ignore=1)}");

    local cmake_args=(${CMAKE_ARGS:-});
    cmake_args+=("-DFIND_LEGATE_CORE_CPP=ON");
    cmake_args+=("-Dlegate_core_ROOT=$REPO_DIR/build");
    cmake_args+=("-DLegion_USE_CUDA=${USE_CUDA:-OFF}");
    cmake_args+=("-DLegion_USE_OpenMP=${USE_OPENMP:-OFF}");


    # Build + package legate.core Python wheel
    time CMAKE_GENERATOR="Ninja" \
         CMAKE_ARGS="${cmake_args[@]}" \
         SKBUILD_BUILD_OPTIONS="${ninja_args[@]}" \
         pip wheel ${pip_args[@]} $REPO_DIR;

}

(build_legate_wheel "$@");
