#!/usr/bin/env bash
set -x

if [ type conda 2>&1 | grep -q function ]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME//miniconda.sh
    bash ~/miniconda.sh -b -p $HOME/miniconda

    if [ -n "${CONDA_EXE:-}" ]; then
        export PATH="$PATH:$CONDA_EXE";
    fi

    cat <<EOF >> $HOME/.bashrc;
    if [ -n "${CONDA_EXE:-}" ]; then
        conda_bin_paths="";
        conda_bin_paths="${conda_bin_paths} $(dirname "$(dirname "${CONDA_EXE}")")/condabin";
        for conda_bin_path in ${conda_bin_paths}; do
            if [ -n "${PATH##*"$conda_bin_path"*}" ]; then
                export PATH="$conda_bin_path:$PATH";
            fi
        done
        unset conda_bin_paths;
    fi
    EOF

    echo "Verify Path is set"
    cat $HOME/.bashrc
fi
