name: Build and test on GH

concurrency:
  group: ci-build-and-test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: gpu
            build-runner: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu32' || 'ubuntu-latest' }}
            platform: linux
            ucx-config: ucx

          - device: gpu
            build-runner: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu32' || 'ubuntu-latest' }}
            platform: linux
            ucx-config: no_ucx

          - device: cpu
            build-runner: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu32' || 'ubuntu-latest' }}
            platform: linux
            ucx-config: ucx

          - device: cpu
            build-runner: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu32' || 'ubuntu-latest' }}
            platform: linux
            ucx-config: no_ucx

          - device: cpu
            build-runner: macos-latest
            platform: osx

    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: ${{ matrix.device }}
      repos-name: ${{ github.event.repository.name }}
      runs-on: ${{ matrix.build-runner }}
      sha: ${{ github.sha }}
      build-type: ci
      use-container: ${{ matrix.platform == 'linux' }}
      ucx-config: ${{ matrix.ucx-config }}
      ucx-string: ${{ (matrix.ucx-config == 'ucx' && '-ucx') || '' }}

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: gpu
            platform: linux
            ucx-config: ucx

          - device: gpu
            platform: linux
            ucx-config: no_ucx

          - device: cpu
            platform: linux
            ucx-config: ucx

          - device: cpu
            platform: linux
            ucx-config: no_ucx

          - device: cpu
            platform: osx
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      device: ${{ matrix.device }}
      platform: ${{ matrix.platform }}